// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fquzkohadtpdfkbqhtjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdXprb2hhZHRwZGZrYnFodGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjkzMjYsImV4cCI6MjA3MDIwNTMyNn0.P7yY78KrqsafB55ksgk9lJHBgb2_UNectqsnEwAEl3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});